pruning_parameters:
  final_temp: 200
  pruning_method: cs
  threshold_decay: 1.0e-09
  threshold_init: 0
training_parameters:
  batch_size: 128
  cosine_tmax: 200
  epochs: 85
  fine_tune: true
  gamma: 0.1
  l2_decay: 0.0001
  label_smoothing: 0.0
  lr: 0.1
  lr_schedule: multistep
  milestones:
  - 56
  - 71
  momentum: 0.9
  optimizer: sgd
  plot_frequency: 100
  pretraining_epochs: 0
  rewind: post-ticket-search
  rounds: 3
  save_weights_epoch: 2
