not_used:
  alpha: -1
  alpha_reset_epoch: -1
  beta: 1.0
  epsilon: -1.0
  max_pruning_pct: -1.0
  pretraining_epochs: 0
  sparsity: 0.8
  temperature: 1.0
  threshold_type: channelwise
pruning_parameters:
  final_temp: 200
  pruning_method: cs
  threshold_init: 0
training_parameters:
  batch_size: 128
  cosine_tmax: 200
  epochs: 85
  fine_tune: true
  gamma: 0.1
  l2_decay: 0.0001
  label_smoothing: 0.0
  lr: 0.1
  lr_schedule: multistep
  milestones:
  - 56
  - 71
  model: resnet18
  momentum: 0.9
  optimizer: sgd
  plot_frequency: 100
  rewind: post-ticket-search
  rounds: 3
  save_weights_epoch: 2
  threshold_decay: 1.0e-09
