name: pquant-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10.16
  - notebook==6.4.12
  - jupyter_contrib_nbextensions
  - jupyterhub
  - jupyter-book
  - jsonschema-with-format-nongpl
  - pydot==1.4.2
  - graphviz==7.1.0
  - scikit-learn==1.2.2
  - webcolors
  - widgetsnbextension==3.6.0
  - pip==23.0.1
  - pip:
      - torchvision
      - matplotlib
      - keras>=3 
      - pyyaml>=6.0.1
      - quantizers>=1.1 
      - torch>=2.1
      - hgq2
