pruning_parameters:
  alpha: 5.0e-06
  max_pruning_pct: 0.99
  pruning_method: dst
  threshold_init: 0.0
  threshold_type: channelwise
training_parameters:
  batch_size: 64
  cosine_tmax: 200
  epochs: 160
  fine_tune: false
  gamma: 0.01
  l2_decay: 0.0001
  label_smoothing: 0.0
  lr: 0.01
  lr_schedule: multistep
  milestones:
  - 80
  - 120
  momentum: 0.9
  optimizer: sgd
  plot_frequency: 100
  pretraining_epochs: 0
  rewind: never
  rounds: 1
  save_weights_epoch: -1
  threshold_decay: 0.0
