pruning_parameters:
  alpha: 0.5
  alpha_reset_epoch: 90
  autotune_epochs: 10
  backward_sparsity: true
  pruning_method: autosparse
  threshold_init: -5.0
  threshold_type: channelwise
training_parameters:
  batch_size: 256
  cosine_tmax: 200
  epochs: 100
  fine_tune: false
  gamma: 0.1
  l2_decay: 3.0517578125e-05
  label_smoothing: 0.1
  lr: 0.01
  lr_schedule: cosine
  milestones:
  - -1
  - -1
  momentum: 0.875
  optimizer: sgd
  plot_frequency: 100
  pretraining_epochs: 0
  rewind: never
  rounds: 1
  save_weights_epoch: -1.0
  threshold_decay: null
