backend: null
batch_size: 128
copy_inputs: false
cross_validation: null
data_config: configs/JetClass_full.yaml
data_fraction: 1
data_test: []
data_train:
- /path/to/particle_transformer/data/JetClass/JetClass/*train*/*.root
data_val: 
- /path/to/particle_transformer/data/JetClass/JetClass/*val*/*/*.root
demo: false
exclude_model_weights: null
export_onnx: null
extra_selection: null
extra_test_selection: null
fetch_by_files: false
fetch_step: 0.01
file_fraction: 1
freeze_model_weights: null
gpus: '0'
in_memory: false
io_test: false
load_epoch: null
load_model_weights: null
log: logs/train.log
lr_finder: null
lr_scheduler: flat+decay
model_prefix: test_model_dst
network_config: ParticleTransformer.py
network_option: []
no_remake_weights: false
num_epochs: 20
num_workers: 0
onnx_opset: 15
optimizer: ranger
optimizer_option: []
predict: false
predict_gpus: null
predict_output: null
print: false
profile: false
regression_mode: false
samples_per_epoch: null
samples_per_epoch_val: null
start_lr: 0.005
steps_per_epoch: 10000
steps_per_epoch_val: 10000
tensorboard: testing_pdp
tensorboard_custom_fn: null
train_val_split: 0.8
use_amp: false
warmup_steps: 0
