pruning_parameters:
  epsilon: 0.015
  pruning_method: pdp
  sparsity: 0.8
  temperature: 1.0e-05
training_parameters:
  batch_size: 256
  cosine_tmax: 200
  epochs: 100
  fine_tuning_epochs: 20
  gamma: 0.1
  l2_decay: 0.0001
  label_smoothing: 0.0
  lr: 0.01
  lr_schedule: cosine
  milestones:
  - -1
  - -1
  momentum: 0.9
  optimizer: sgd
  plot_frequency: 100
  pretraining_epochs: 16
  rewind: never
  rounds: 1
  save_weights_epoch: -1
  threshold_decay: 0.
